### ISSUE TITLE
Add functional tests for AndroidEventHistoryDatabase

### ISSUE THREAD

**Issue by spoorthipujariadobe** [adobe/aepsdk-core-android#100]

**Comment by praveek** [comment]
https://github.com/adobe/aepsdk-core-android/blob/dev-v2.0.0/code/android-core-library/src/androidTest/java/com/adobe/marketing/mobile/internal/eventhub/history/AndroidEventHistoryTests.java

https://github.com/adobe/aepsdk-core-android/blob/dev-v2.0.0/code/android-core-library/src/androidTest/java/com/adobe/marketing/mobile/internal/eventhub/history/AndroidEventHistoryDatabaseTests.java
