### ISSUE TITLE
[discussion] should we still keep releasing the sdk-core 2.0 artifact

### ISSUE THREAD

**Issue by yangyansong-adbe** [adobe/aepsdk-core-android#105]
Not like ACPCore, AEPCore doesn't include Signal/Identity/Lifecycle binaries. Should we consider doing the same for the `2.0` Android SDKs? If so, we can remove this [maven-root sub-project](https://github.com/adobe/aepsdk-core-android/tree/main/code/android-core-library-maven-root) and not release sdk-core 2.x builds.
What is the rule to version the core extensions in Android 2.x SDKs? We use a uniform version for Swift core extensions, should we follow this convention in Android 2.x?

**Comment by praveek** [comment]
Discussed internally and decided not to keep to `sdk-core` artifact. Instead, apps will have to include `core`, `signal`, `identity` and `lifecycle` based on their use case. 
This will also reflect in the new install instructions once they update the MobileCore extension inside Launch mobile property.
