### ISSUE TITLE
[discussion] HitQueue database migration

### ISSUE THREAD

**Issue by yangyansong-adbe** [adobe/aepsdk-core-android#142]
We have decided to remove the internal HitQueue service and make extensions migrate to use the new public HitQueue service. For more details check on this PR: https://github.com/adobe/aepsdk-core-android/pull/77
We need to decide if the `hits` stored in the old HitQueue database need to be migrated to the new database.

**Comment by praveek** [comment]
After internal discussion, we decided not to migrate hits from old HitQueue databases.
