### ISSUE TITLE
[docs] add public docs for the newly added API -> setURIHandler & getIntentWithURI

### ISSUE THREAD

**Issue by yangyansong-adbe** [adobe/aepsdk-core-android#16]
Two APIs will be added to Core 2.0.0 for security improvement https://github.com/adobe/aepsdk-core-android/pull/15. In addition, the public docs need to be updated once Core-2.0.0 is released.

**Comment by praveek** [comment]
Tracking it here https://github.com/AdobeDocs/aep-mobile-sdkdocs/issues/145
