### ISSUE TITLE
Add functionality to extract and cache assets in the RulesLoader

### ISSUE THREAD

**Issue by rymorale** [adobe/aepsdk-core-android#250]
### Expected Behaviour
- Campaign rules are delivered alongside an assets directory containing the html files for each fullscreen in-app message defined in the rules json:
<img width="732" alt="campaign_rule_assets" src="https://user-images.githubusercontent.com/11319121/198371685-0269c2e4-69ae-49c0-bf1c-20e4c114a593.png">

Functionality is needed to also cache these html assets when unzipping the Campaign rules.zip.

**Comment by praveek** [comment]
This is no longer required as the functionality was implemented in the Campaign extension.
