### ISSUE TITLE
2.0.0 changelog documentation

### ISSUE THREAD

**Issue by G00fY2** [adobe/aepsdk-core-android#394]
Is there/will there be a proper changelog or migration guide for all the Adobe 2.0 library updates (core, assurance, analytics ...) in the official [documentation](https://developer.adobe.com/client-sdks/documentation/release-notes/)?

I think the GitHub changelog is just a list of the commits and doesn't really help to grasp the important changes.

**Comment by cdhoffmann** [comment]
@G00fY2 Documentation for the new Android release is being worked on by the team, and is being tracked internally (which is why there are no github issues for it). Thank you for your concern, we will make sure and comment here once it is complete.

**Comment by praveek** [comment]
@G00fY2 The Android SDK 2.0 is ready to use. For more details, please see the release notes: [developer.adobe.com/client-sdks/documentation/release-notes/#february-23-2023](https://developer.adobe.com/client-sdks/documentation/release-notes/#february-23-2023)
