### ISSUE TITLE
When will the BoM be available?

### ISSUE THREAD

**Issue by G00fY2** [adobe/aepsdk-core-android#412]
Looks like a BoM was added for the Adobe dependencies: #402

Any ETA when this will be available on [MavenCentral](https://central.sonatype.com/namespace/com.adobe.marketing.mobile)?

**Comment by yangyansong-adbe** [comment]
@G00fY2 We're still finalizing something internally. We don't have an ETA at this point in time, but the release should be available very soon. I will keep you updated. 

Thanks,
Yansong

**Comment by yangyansong-adbe** [comment]
Hi @G00fY2 ,
The [beta build](https://central.sonatype.com/artifact/com.adobe.marketing.mobile/sdk-bom/1.0.0-beta1) for the BOM artifact is released. Please give it a try when you have time, and we would appreciate any feedback. 

Thanks,
Yansong

**Comment by G00fY2** [comment]
@yangyansong-adbe We just switched to the new BOM and removed all adobe version references. We use a setup with Gradle version catalog (.toml) and Kotlin Script Gradle buildscripts. We have not faced any issues so far. 👍 

PS: I think the BOM is more in the state of an RC rather than beta, right?

**Comment by G00fY2** [comment]
@yangyansong-adbe In the meantime there was the release of core 2.1.2 and 2.1.3 and also the release of assurance 2.1.0. Will this BOM be updated any time soon? Otherwise there is no point in using it and we would need to switch back to separately maintaining the version numbers.

**Comment by yangyansong-adbe** [comment]
Hi @G00fY2 , we're working on adding more scripts for the BOM release automation. We will release an RC build for BOM next week, including the latest SDKs.

**Comment by jahunt1** [comment]
Having a current BOM will help my team manage our Adobe dependencies too. +1 for this issue.

**Comment by yangyansong-adbe** [comment]
Hi @G00fY2 , @jahunt1 
Close this issue now because the BOM artifact 1.0.0 was released last week. Please take a look at the release notes here: https://developer.adobe.com/client-sdks/documentation/release-notes/#june-1-2023. 
 

Thanks,
Yansong

**Comment by G00fY2** [comment]
@yangyansong-adbe Any update on v3 BoM? 😃

**Comment by yangyansong-adbe** [comment]
@G00fY2 After we release all SDK extensions, BOM 3.0.0 will be released later this week.
