### ISSUE TITLE
Make updateConfiguration API environment aware

### ISSUE THREAD

**Issue by kevinlind** [adobe/aepsdk-core-android#539]
### Expected Behaviour
Calling `MobileCore.updateConfiguration()` should update the current environment's configuration key instead of exact key matches, similar to the iOS implementation.

### Actual Behaviour
Calling `MobileCore.updateConfiguration()` will update the exact key match for environment prefixed keys. Meaning, calling `MobileCore.updateConfiguration(mapOf("analytics.rsids" to "mynew.rsid"))` will update the "analytics.rsids" value instead of the "__dev__analytics.rsids" value when the environment is "dev".

#### Steps to Reproduce
Use the "testapp-kotlin":
Update ADBMobileConfig.json by adding environment aware keys:
```
"analytics.rsids": "pro.rsid",
"__dev__analytics.rsids": "dev.rsid"
```
Update CoreView.kt by changing the parameter in the updateConfiguration call
```
MobileCore.updateConfiguration(mapOf("analytics.rsids" to "mynew.rsid"))
```
Run the application, notice the configuration response event includes "analytics.rsids: dev.rsid".
Click the UpdateConfiguration button and notice the configuration response event still includes "analytics.rsids: dev.rsid"

**Comment by prudrabhat** [comment]
Fixed as part of https://github.com/adobe/aepsdk-core-android/pull/541.  Will be a part of the next core release.
