### ISSUE TITLE
Support Notification UI in UIServices v-next

### ISSUE THREAD

**Issue by prudrabhat** [adobe/aepsdk-core-android#553]
### Expected Behaviour
Add the ability for service clients (Campaign now, and Messaging soon) to create a notification using the UIService.
- Investigate if the current notification building and dispatching logic can be moved into UIService allowing clients to be agnostic of the activity/receiver related logic.
- Simplify or migrate the logic in `LocalNotificationHandler`

**Comment by prudrabhat** [comment]
UIService contract currently supports `Presentables` that can be displayed within the host app ui. More specifically, they are UI's that are tied to the apps lifecycle i.e live only as long as the app ui lives. This allows the UIService to access the `PresentationEventListener`s and the `PresentationEventHandler`s for these `Presentables` without the needing to worry about persisting them beyond the app lifecycle.

My initial thinking was to have a similar paradigm for notifications i.e have a `Notification` presentation, `NotificationSettings` that define the settings/features for it and a `NotificationEventListener` for components to get notified about the notification taps or button clicks or dismissals by creating a trampoline activity that receives these intents that arise from interactions on notifications. However, notifications outlive the app lifecycle after they are initially fired and presented.  The intent can resume the app or re-launch the app. This means that for `UIService` to notify the right `NotificationEventListener` for the notification, it should have a mechanism to persist this information across app launches! Due to `NotificationEventListener` being an interface which can have custom implementations - it cannot be trivially parcelable or serializable for use later. Overall, it does not fit with the contracts for the current api UIService exposes. 

Campaign uses notifications now, and MessagingExtension is looking to add support for it soon, Following possibilities come to mind: 
1.  Have Campaign and Messaging handle notifications independently.
2.  Create a `NotificationService` that has a contract that allows components to register one listener per component and associate intents with an id for this listener. These listeners will only be capable of notifying the `Intent` associated with notification to the listener.
3.  Include option#2 within UIService (😞)

@praveek , @PravinPK , @sbenedicadb - Thoughts?

**Comment by praveek** [comment]
I prefer Option 1 because of its simplicity. UIService was initially created for presenting UI components associated with application's lifecycle and supporting notifications would introduce added complexity.
