### ISSUE TITLE
DataReader.getString is not throwing an exception when the string value is not present in the map

### ISSUE THREAD

**Issue by rymorale** [adobe/aepsdk-core-android#570]
### Expected Behaviour
A DataReaderException should be thrown if the requested key is not present in the given map
#### Platform and Version
Android AEPSDK Core 2.4.0
#### Sample Code that illustrates the problem
```java
Map<String, Object> map = new HashMap<String, Object>() {{ put("key", "value"); }};
        try {
            String retValue = DataReader.getString(map, "key2");
        } catch (DataReaderException exception) {
            // this should fail but doesn't
            Assert.fail();
        }
```

**Comment by prudrabhat** [comment]
@rymorale - `DataReader.getString(..)` is [documented](https://github.com/adobe/aepsdk-core-android/blob/main/code/core/src/main/java/com/adobe/marketing/mobile/util/DataReader.java#L540) as follows :
```
 @return {@code String} value associated with {@code key} or null if {@code key} is not
     *     present in {@code map}
     * @throws DataReaderException if value is not gettable as an {@code String}
```
So it is expected to return null if the key is absent. DataReaderException is thrown when the key exists but is not a string.
