### ISSUE TITLE
[Android][Core 3.0.0] Long in-app messages without gestures are not scrollable

### ISSUE THREAD

**Issue by rymorale** [adobe/aepsdk-core-android#638]
### Expected Behaviour
Long in-app messages can be scrolled by clicking then dragging in the desired scroll direction.
### Actual Behaviour
Long in-app messages cannot be scrolled.
#### Steps to Reproduce
1. Create an in-app campaign with the attached html:
[long-iam.html.zip](https://github.com/adobe/aepsdk-core-android/files/14856447/long-iam.html.zip)
2. Trigger the iam on an android device
#### Platform and Version
Android Core 3.0.0

**Comment by prudrabhat** [comment]
Fixed as part of https://github.com/adobe/aepsdk-core-android/pull/640 
Will be available in the upcoming Core release.
