### ISSUE TITLE
HttpConnecting.getResponsePropertyValue is case-sensitive

### ISSUE THREAD

**Issue by emdobrin** [adobe/aepsdk-core-android#719]
### Expected Behaviour
Response headers should be treated as case-insensitive keys as per [RFC 2616 section 4.2](https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2), however HttpConnection#getResponsePropertyValue treats them as case-sensitive. 

Add tests for headers with mixed-cases.

#### Steps to Reproduce
Use Android Studio Network Inspector, set up a Rule and add response headers, then read those in the SDK using exact match or mixed matches.

#### Platform and Version
Android, Core 3.0.0

**Comment by praveek** [comment]
URLConnection's getHeaderField method is already case-insensitive.
