### ISSUE TITLE
DataQueue public interface ambiguous method names

### ISSUE THREAD

**Issue by spoorthipujariadobe** [adobe/aepsdk-core-android#82]
### Expected Behaviour

We have multiple versions of methods called peek() and remove() which return/remove n items instead of a single item as is the case with traditional queue. Would be nice to have different method names like peekNElements() and removeNElements to clarify the purpose.

https://github.com/adobe/aepsdk-core-android/blob/9cee4f8d4b688002a2ea217b0d907848ae0859cc/code/android-core-library/src/main/java/com/adobe/marketing/mobile/services/DataQueue.java#L37

**Comment by praveek** [comment]
Closing this as these APIs are already public from 1.8
